name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build With Maven
        run: mvn clean package -B

      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deployment Done
        run: echo "Image pushed! Pull and run it with Docker Desktop on your PC."
